/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put your custom code here.
 */
package org.graniteds.tutorial.data.client;

import org.granite.client.messaging.RemoteAlias;
import org.granite.client.persistence.Entity;
import org.granite.messaging.annotations.Serialized;

@Entity
@Serialized
@RemoteAlias("org.graniteds.tutorial.data.entities.Box")
public class Box extends BoxBase {

    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        return "Box{id=" + getId() + ",name=" + getName() + "}";
    }
}
